"""audio

Revision ID: 71cdd40d5af2
Revises: fcf1cfbd25cf
Create Date: 2024-12-07 04:26:14.389722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cdd40d5af2'
down_revision: Union[str, None] = 'fcf1cfbd25cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('audio_file_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'audio_file_path')
    # ### end Alembic commands ###
